### ISSUE TITLE
encodeLastAction gives wrong relativeIdx value

### ISSUE THREAD

**Issue by hoseasiu** [facebookresearch/Hanabi_SPARTA#26]
In a two-player game, `encodeLastAction`'s `relativeIdx` variable always points to the same index, making it wrong half the time. The calculation for it also seems unnecessarily complicated - for example, there's a (`numPlayers` + X)%`numPlayers` calculation, which just equals X. 

https://github.com/facebookresearch/Hanabi_SPARTA/blob/88edc9f20c3f59d03bab11f43a441fdfa8bcf24b/csrc/HleUtils.h#L248

I tested this line changed to just `int relativeIdx = lastActivePlayer;` which seems to have resolved the issue, since player numbers are zero-indexed, and so is the one-hot encoding that this portion of the observation space is referring to.

**Comment by hengyuan-hu** [comment]
This is the "relative" index of the previous active player. In a two player setting, if previous player was me, then `relativeIdx = 0`, if it was not me, then `relativeIdx = 1`. For the current active player this should indeed be always 1. Please let me know if it is the same regardless of whether "me" is the current active player. 

In C++, `(numPlayers + x) % num_players != x % num_players` when `x < 0`. e.g. `std::cout << -1 % 5 << std::endl` may return -1. See https://stackoverflow.com/questions/7594508/modulo-operator-with-negative-values.

This part of the code is trying to implement the encoding in HLE. Here, they have converted last_move to be ego centric, i.e. `last_move.player_id` is relative id not absolute. https://github.com/deepmind/hanabi-learning-environment/blob/54e79594f4b6fb40ebb3004289c6db0e34a8b5fb/hanabi_learning_environment/hanabi_lib/canonical_encoders.cc#L248

**Comment by hoseasiu** [comment]
I see, the ego-centric frame is an interesting choice for HLE, but yes, that does seem to be the case, and matches with some other testing I just did. We were trying to use it as a way to determine when to log a game state, since observations are made more than once per turn, but we'll figure out a way around it.

Thanks!
